spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://localhost/sell?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
  jackson:
    default-property-inclusion: non_null
#  redis:
#    host: 192.168.30.113
#    port: 6379
server:
  context-path: /sell


wechat:
  mpAppId: wx23579bb01322caaa
  mpAppSecret: c401ff81bad41aedfd849495373a19c9