
package com.cky.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import java.util.List;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "CustomerService", targetNamespace = "http://service.crm.cky.com/")
@XmlSeeAlso({
})
public interface CustomerService {


    /**
     * 
     * @param arg0
     * @return
     *     returns com.cky.crm.service.Customer
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findById", targetNamespace = "http://service.crm.cky.com/", className = "com.cky.crm.service.FindById")
    @ResponseWrapper(localName = "findByIdResponse", targetNamespace = "http://service.crm.cky.com/", className = "com.cky.crm.service.FindByIdResponse")
    public Customer findById(
            @WebParam(name = "arg0", targetNamespace = "")
                    Object arg0);

    /**
     * 
     * @return
     *     returns java.util.List<com.cky.crm.service.Customer>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findAll", targetNamespace = "http://service.crm.cky.com/", className = "com.cky.crm.service.FindAll")
    @ResponseWrapper(localName = "findAllResponse", targetNamespace = "http://service.crm.cky.com/", className = "com.cky.crm.service.FindAllResponse")
    public List<Customer> findAll();

}
