spring:
  mvc:
    view:
      prefix: /WEB-INF/center/
      suffix: .jsp
    thymeleaf:
      cache: false
      enabled: false
  datasource:
    url: jdbc:mysql://129.204.109.238:3306/weixin-dev?characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: ckySaltedFish

    druid:
      initial-size: 5
      min-idle: 20
      max-active: 50
      max-wait: 30000 # 30s
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 'x'
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: false
      max-pool-prepared-statement-per-connection-size: 0
      filters: config,mergeStat,wall
      remove-abandoned: true
      remove-abandoned-timeout: 60
      log-abandoned: true
      max-evictable-idle-time-millis: 300000
      max-open-prepared-statements: 20
      validation-query-timeout: 60 # 60s
      time-between-eviction-runs-millis: 60000
      # WebStatFilter\u914D\u7F6E\uFF0C\u8BF4\u660E\u8BF7\u53C2\u8003Druid Wiki\uFF0C\u914D\u7F6E_\u914D\u7F6EWebStatFilter
      web-stat-filter:
        enabled: true
        # url-pattern:
        # exclusions:
        # session-stat-enable: true
        # session-stat-max-count:
        # principal-session-name:
        # principal-cookie-name:
        # profile-enable:
      # StatViewServlet\u914D\u7F6E\uFF0C\u8BF4\u660E\u8BF7\u53C2\u8003Druid Wiki\uFF0C\u914D\u7F6E_StatViewServlet\u914D\u7F6E
      stat-view-servlet:
        enabled: true
        # url-pattern:
        reset-enable: false
        login-username: druid
        login-password: druid




  devtools:
    restart:
      enabled: true  #设置开启热部署

#  resources:
#    static-locations: classpath:/META-INF/resources/static/**



  #mybatis
  mybatis-plus:
    mapper-locations: classpath:mapper/*.xml
    #\u5B9E\u4F53\u626B\u63CF\uFF0C\u591A\u4E2Apackage\u7528\u9017\u53F7\u6216\u8005\u5206\u53F7\u5206\u9694
    typeAliasesPackage: com.cky.entity
    global-config:
      # \u6570\u636E\u5E93\u76F8\u5173\u914D\u7F6E
      db-config:
        #\u4E3B\u952E\u7C7B\u578B  AUTO:"\u6570\u636E\u5E93ID\u81EA\u589E", INPUT:"\u7528\u6237\u8F93\u5165ID",ID_WORKER:"\u5168\u5C40\u552F\u4E00ID (\u6570\u5B57\u7C7B\u578B\u552F\u4E00ID)", UUID:"\u5168\u5C40\u552F\u4E00ID UUID";
        id-type: AUTO
        #\u5B57\u6BB5\u7B56\u7565 IGNORED:"\u5FFD\u7565\u5224\u65AD",NOT_NULL:"\u975E NULL \u5224\u65AD"),NOT_EMPTY:"\u975E\u7A7A\u5224\u65AD"
        field-strategy: not_empty
        #\u9A7C\u5CF0\u4E0B\u5212\u7EBF\u8F6C\u6362
        column-underline: true
        #\u6570\u636E\u5E93\u5927\u5199\u4E0B\u5212\u7EBF\u8F6C\u6362
        #capital-mode: true
        #\u903B\u8F91\u5220\u9664\u914D\u7F6E
        logic-delete-value: 0
        logic-not-delete-value: 1
        db-type: mysql
      #\u5237\u65B0mapper \u8C03\u8BD5\u795E\u5668
      refresh: true
    # \u539F\u751F\u914D\u7F6E
    configuration:
      map-underscore-to-camel-case: true
      cache-enabled: false
server:
  port: 8087